version: '3'

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.75.0
    environment:
      UPTRACE_DSN: ${UPTRACE_DSN}
    volumes:
      - ./collector.yml:/conf/collector.yml
    command: ['--config=/conf/collector.yml']

  php-fpm:
    image: php:8.1.11-fpm
    volumes:
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf

  php-fpm-exporter:
    image: hipages/php-fpm_exporter:2.2.0
    command: ['--phpfpm.scrape-uri', 'tcp://php-fpm:9000/status']
